site_name: Urban Mobility Data Hub
site_description: "FIWARE-based Data Space for Smart Mobility"
repo_url: https://github.com/urban-mobility-data-hub/urban-mobility-data-hub.github.io

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: white     # color principal del header
      accent: amber       # color de botones y enlaces activos
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - content.code.copy
    - content.tabs.link


extra_css:
  - assets/css/custom.css

nav:
  - Inicio: index.md
  - Arquitectura: stack.md
  - Guía de despliegue: deploy-guide.md
  - Conectar al dataspace: onboarding.md
  - Usar el dataspace:
    - tokens: tokens.md
    - Datos: datos.md
    - Políticas: politicas.md
    - TM Forum API: tmforum.md
  - Seguridad, autenticación y autorización: security.md

